### ISSUE TITLE
无法导包

### ISSUE THREAD

**Issue by controlFate** [244317809/flutter_gm_cipher#1]
使用pub get 加载了插件，但是导包失败，查找不到。Target of URI doesn't exist: 'package:flutter_gm_cipher/flutter_gm_cipher.dart'.

**Comment by 244317809** [comment]
不好意思现在才看到，我刚才新建了一个项目导入（`  flutter_gm_cipher: ^0.0.6`），没发现这个问题，你也建个空工程测试下吧

**Comment by 244317809** [comment]
> 使用pub get 加载了插件，但是导包失败，查找不到。Target of URI doesn't exist: 'package:flutter_gm_cipher/flutter_gm_cipher.dart'.

不好意思现在才看到，我刚才新建了一个项目导入（ flutter_gm_cipher: ^0.0.6），没发现这个问题，你也建个空工程测试下吧
